# Generated by Django 4.2.27 on 2025-12-11 20:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('clients', '0001_initial'),
        ('vendors', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start date of the reporting period', verbose_name='Period Start')),
                ('period_end', models.DateField(help_text='End date of the reporting period', verbose_name='Period End')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total sales revenue', max_digits=12, verbose_name='Total Revenue')),
                ('total_cost_of_goods_sold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of goods sold', max_digits=12, verbose_name='Cost of Goods Sold')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total operating expenses', max_digits=12, verbose_name='Total Expenses')),
                ('gross_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit (Revenue - COGS)', max_digits=12, verbose_name='Gross Profit')),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net profit (Gross Profit - Expenses)', max_digits=12, verbose_name='Net Profit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Profit/Loss',
                'verbose_name_plural': 'Profit/Loss Reports',
                'ordering': ['-period_end'],
                'unique_together': {('period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('payment_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], help_text='Credit (money in) or Debit (money out)', max_length=10, verbose_name='Payment Type')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('ONLINE', 'Online Payment'), ('OTHER', 'Other')], default='BANK_TRANSFER', help_text='Method of payment', max_length=20, verbose_name='Payment Method')),
                ('date', models.DateField(help_text='Date of the payment', verbose_name='Payment Date')),
                ('description', models.TextField(help_text='Description or notes about the payment', verbose_name='Description')),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number (check number, transfer ID, etc.)', max_length=100, null=True, verbose_name='Reference Number')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this payment has been reconciled', verbose_name='Is Reconciled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(blank=True, help_text='Client/customer for client payments', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client', verbose_name='Client')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Related purchase order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='purchases.purchaseorder', verbose_name='Purchase Order')),
                ('sales_order', models.ForeignKey(blank=True, help_text='Related sales order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.salesorder', verbose_name='Sales Order')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor/supplier for vendor payments', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the ledger entry', verbose_name='Entry Date')),
                ('description', models.TextField(help_text='Description of the ledger entry', verbose_name='Description')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Debit amount (money out)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Debit Amount')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit amount (money in)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Credit Amount')),
                ('entry_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('ADJUSTMENT', 'Adjustment'), ('OTHER', 'Other')], default='OTHER', help_text='Type of ledger entry', max_length=20, verbose_name='Entry Type')),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (e.g., PAYMENT, SALES_ORDER)', max_length=50, null=True, verbose_name='Reference Type')),
                ('reference_id', models.IntegerField(blank=True, help_text='ID of the referenced object', null=True, verbose_name='Reference ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('payment', models.ForeignKey(blank=True, help_text='Related payment (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['vendor'], name='accounts_pa_vendor__bac997_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['client'], name='accounts_pa_client__4601d3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='accounts_pa_date_2803cb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='accounts_pa_payment_c24ace_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['purchase_order'], name='accounts_pa_purchas_4ec2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['sales_order'], name='accounts_pa_sales_o_e6ce26_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['date'], name='accounts_le_date_f38996_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['entry_type'], name='accounts_le_entry_t_dd0637_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference_type', 'reference_id'], name='accounts_le_referen_e193f9_idx'),
        ),
    ]
