# Generated by Django 4.2.27 on 2025-12-11 20:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique purchase order number', max_length=50, unique=True, verbose_name='Order Number')),
                ('order_date', models.DateField(help_text='Date when the purchase order was created', verbose_name='Order Date')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected date of delivery', null=True, verbose_name='Expected Delivery Date')),
                ('received_date', models.DateField(blank=True, help_text='Date when the order was received', null=True, verbose_name='Received Date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount of the purchase order', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('PARTIAL', 'Partially Received'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the purchase order', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the purchase order', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('vendor', models.ForeignKey(help_text='Vendor/supplier for this purchase order', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='vendors.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of items ordered', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Cost')),
                ('freight_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Freight/shipping cost allocated to this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Freight Cost')),
                ('customs_duty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Customs duty/tariff cost allocated to this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Customs Duty')),
                ('other_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Other costs (insurance, handling, etc.) allocated to this item', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Other Costs')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total cost for this line (quantity * unit_cost)', max_digits=12, verbose_name='Line Total')),
                ('landed_cost_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total landed cost per unit including all additional costs', max_digits=10, verbose_name='Landed Cost Per Unit')),
                ('total_landed_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total landed cost for this line item', max_digits=12, verbose_name='Total Landed Cost')),
                ('received_quantity', models.IntegerField(default=0, help_text='Quantity actually received', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Received Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(help_text='Product/item being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.item', verbose_name='Item')),
                ('purchase_order', models.ForeignKey(help_text='Purchase order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='purchases.purchaseorder', verbose_name='Purchase Order')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'ordering': ['purchase_order', 'item'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='purchases_p_order_n_2fe609_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor'], name='purchases_p_vendor__9b73dd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchases_p_order_d_6d1057_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchases_p_status_7fddca_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase_order'], name='purchases_p_purchas_e4d990_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['item'], name='purchases_p_item_id_6e51c3_idx'),
        ),
    ]
