# Generated by Django 4.2.27 on 2025-12-11 20:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product category', max_length=100, unique=True, verbose_name='Category Name')),
                ('code', models.CharField(help_text='Short code for the category', max_length=20, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the category', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is currently active', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product/item', max_length=200, verbose_name='Item Name')),
                ('sku', models.CharField(help_text='Stock Keeping Unit - unique identifier', max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, help_text='Barcode or UPC code', max_length=100, null=True, unique=True, verbose_name='Barcode')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the item', null=True, verbose_name='Description')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Purchase cost per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cost Price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Retail selling price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Selling Price')),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('BOX', 'Box'), ('PKG', 'Package'), ('SET', 'Set'), ('PAIR', 'Pair'), ('KG', 'Kilogram'), ('L', 'Liter'), ('M', 'Meter')], default='PCS', help_text='Unit of measurement for this item', max_length=10, verbose_name='Unit of Measurement')),
                ('reorder_level', models.IntegerField(default=0, help_text='Minimum stock level before reordering', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reorder Level')),
                ('reorder_quantity', models.IntegerField(default=0, help_text='Standard quantity to reorder', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reorder Quantity')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight per unit in kilograms', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Weight (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='Dimensions (L x W x H)', max_length=50, null=True, verbose_name='Dimensions')),
                ('vehicle_make', models.CharField(blank=True, help_text='Compatible vehicle manufacturer', max_length=50, null=True, verbose_name='Vehicle Make')),
                ('vehicle_model', models.CharField(blank=True, help_text='Compatible vehicle model', max_length=50, null=True, verbose_name='Vehicle Model')),
                ('vehicle_year_from', models.IntegerField(blank=True, help_text='Earliest compatible vehicle year', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Vehicle Year From')),
                ('vehicle_year_to', models.IntegerField(blank=True, help_text='Latest compatible vehicle year', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Vehicle Year To')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently active', verbose_name='Is Active')),
                ('is_trackable', models.BooleanField(default=True, help_text='Whether stock levels should be tracked for this item', verbose_name='Is Trackable')),
                ('allow_backorder', models.BooleanField(default=False, help_text='Whether backorders are allowed when out of stock', verbose_name='Allow Backorder')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/images/', verbose_name='Item Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category', verbose_name='Category')),
                ('vendor', models.ForeignKey(blank=True, help_text='Primary supplier/vendor for this item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='vendors.vendor', verbose_name='Primary Vendor')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the warehouse or storage location', max_length=100, unique=True, verbose_name='Warehouse Name')),
                ('code', models.CharField(help_text='Short code for the warehouse', max_length=20, unique=True, verbose_name='Warehouse Code')),
                ('address', models.TextField(help_text='Physical address of the warehouse', verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province')),
                ('country', models.CharField(default='USA', max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manager Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this warehouse is currently active', verbose_name='Is Active')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Total storage capacity (in square meters or cubic meters)', max_digits=10, null=True, verbose_name='Capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_w_name_703b74_idx'), models.Index(fields=['code'], name='inventory_w_code_2cdc02_idx'), models.Index(fields=['is_active'], name='inventory_w_is_acti_3ddeac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Quantity reserved for pending orders', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reserved Quantity')),
                ('available_quantity', models.IntegerField(default=0, editable=False, help_text='Available quantity (quantity - reserved)', verbose_name='Available Quantity')),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum stock level for this warehouse', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Quantity')),
                ('max_quantity', models.IntegerField(blank=True, help_text='Maximum stock level for this warehouse', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Quantity')),
                ('average_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average cost per unit for this stock', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Average Cost')),
                ('last_restocked', models.DateTimeField(blank=True, help_text='Date and time of last restocking', null=True, verbose_name='Last Restocked')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(help_text='Product/item', on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.item', verbose_name='Item')),
                ('warehouse', models.ForeignKey(help_text='Warehouse location', on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['item', 'warehouse'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.IntegerField(help_text='Stock quantity when alert was created', verbose_name='Current Quantity')),
                ('min_quantity', models.IntegerField(help_text='Minimum required quantity', verbose_name='Minimum Quantity')),
                ('alert_status', models.CharField(choices=[('PENDING', 'Pending'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='PENDING', help_text='Status of the alert', max_length=20, verbose_name='Alert Status')),
                ('message', models.TextField(help_text='Alert message', verbose_name='Alert Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged At')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('item', models.ForeignKey(help_text='Item that triggered the alert', on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.item', verbose_name='Item')),
                ('stock', models.ForeignKey(help_text='Stock entry that triggered the alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.stock', verbose_name='Stock')),
                ('warehouse', models.ForeignKey(help_text='Warehouse where the alert occurred', on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock Alert',
                'verbose_name_plural': 'Stock Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse'], name='inventory_s_warehou_6b834f_idx'), models.Index(fields=['item'], name='inventory_s_item_id_554ff6_idx'), models.Index(fields=['alert_status'], name='inventory_s_alert_s_b1e150_idx'), models.Index(fields=['created_at'], name='inventory_s_created_671808_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['item', 'warehouse'], name='inventory_s_item_id_6bc180_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['quantity'], name='inventory_s_quantit_287c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['warehouse'], name='inventory_s_warehou_ecb923_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('item', 'warehouse')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['sku'], name='inventory_i_sku_3e99d5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_209767_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['name'], name='inventory_i_name_637656_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category'], name='inventory_i_categor_dcc1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['vendor'], name='inventory_i_vendor__c83d21_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['is_active'], name='inventory_i_is_acti_fd4174_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['vehicle_make', 'vehicle_model'], name='inventory_i_vehicle_7cbe5a_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='inventory_c_name_546ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code'], name='inventory_c_code_710414_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='inventory_c_is_acti_63d81f_idx'),
        ),
    ]
