# Generated by Django 4.2.27 on 2025-12-11 20:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Unique sales order number', max_length=50, unique=True, verbose_name='Order Number')),
                ('order_date', models.DateField(help_text='Date when the sales order was created', verbose_name='Order Date')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected date of delivery', null=True, verbose_name='Expected Delivery Date')),
                ('shipped_date', models.DateField(blank=True, help_text='Date when the order was shipped', null=True, verbose_name='Shipped Date')),
                ('delivered_date', models.DateField(blank=True, help_text='Date when the order was delivered', null=True, verbose_name='Delivered Date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount of the sales order', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total discount applied to the order', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of the sales order', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the sales order', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(help_text='Client/customer for this sales order', on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='clients.client', verbose_name='Client')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse from which items will be shipped', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of items ordered', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Unit Price')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage for this line item', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Discount Percentage')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total amount for this line item', max_digits=12, verbose_name='Line Total')),
                ('shipped_quantity', models.IntegerField(default=0, help_text='Quantity actually shipped', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Shipped Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item', models.ForeignKey(help_text='Product/item being sold', on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='inventory.item', verbose_name='Item')),
                ('sales_order', models.ForeignKey(help_text='Sales order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sales_items', to='sales.salesorder', verbose_name='Sales Order')),
            ],
            options={
                'verbose_name': 'Sales Item',
                'verbose_name_plural': 'Sales Items',
                'ordering': ['sales_order', 'item'],
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_number'], name='sales_sales_order_n_78c57a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['client'], name='sales_sales_client__2d59a0_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['order_date'], name='sales_sales_order_d_55e46c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status'], name='sales_sales_status_480214_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['warehouse'], name='sales_sales_warehou_2c77af_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['sales_order'], name='sales_sales_sales_o_1d54a8_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['item'], name='sales_sales_item_id_ef3e43_idx'),
        ),
    ]
