# Generated by Django 4.2.27 on 2025-12-11 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the client/customer company or individual', max_length=200, unique=True, verbose_name='Client Name')),
                ('code', models.CharField(blank=True, help_text='Short code for the client', max_length=50, null=True, unique=True, verbose_name='Client Code')),
                ('country', models.CharField(help_text='Country where the client is located', max_length=100, verbose_name='Country')),
                ('city', models.CharField(help_text='City where the client is located', max_length=100, verbose_name='City')),
                ('contact_number', models.CharField(help_text='Primary contact phone number', max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('address', models.TextField(blank=True, help_text='Street address', null=True, verbose_name='Address')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True, verbose_name='Website')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True, verbose_name='Tax ID')),
                ('payment_terms', models.CharField(blank=True, help_text='Standard payment terms (e.g., Net 30, Net 60, COD)', max_length=100, null=True, verbose_name='Payment Terms')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit for this client', max_digits=12, null=True, verbose_name='Credit Limit')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard discount percentage for this client', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this client is currently active', verbose_name='Is Active')),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('RETAILER', 'Retailer'), ('WHOLESALER', 'Wholesaler'), ('DISTRIBUTOR', 'Distributor'), ('DEALER', 'Dealer'), ('OTHER', 'Other')], default='RETAILER', help_text='Type of client/customer', max_length=20, verbose_name='Client Type')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the client', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'), models.Index(fields=['code'], name='clients_cli_code_d90b4a_idx'), models.Index(fields=['country'], name='clients_cli_country_9270e5_idx'), models.Index(fields=['city'], name='clients_cli_city_7aacf1_idx'), models.Index(fields=['is_active'], name='clients_cli_is_acti_57c1e7_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx'), models.Index(fields=['client_type'], name='clients_cli_client__1e0f73_idx')],
            },
        ),
    ]
