# Generated by Django 4.2.27 on 2025-12-11 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the vendor/supplier company', max_length=200, unique=True, verbose_name='Vendor Name')),
                ('code', models.CharField(blank=True, help_text='Short code for the vendor', max_length=50, null=True, unique=True, verbose_name='Vendor Code')),
                ('country', models.CharField(help_text='Country where the vendor is located', max_length=100, verbose_name='Country')),
                ('contact_number', models.CharField(help_text='Primary contact phone number', max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(help_text='Primary email address', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('address', models.TextField(blank=True, help_text='Street address', null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('website', models.URLField(blank=True, help_text='Company website URL', null=True, verbose_name='Website')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True, verbose_name='Tax ID')),
                ('payment_terms', models.CharField(blank=True, help_text='Standard payment terms (e.g., Net 30, Net 60)', max_length=100, null=True, verbose_name='Payment Terms')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit for this vendor', max_digits=12, null=True, verbose_name='Credit Limit')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this vendor is currently active', verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the vendor', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='vendors_ven_name_0d60a8_idx'), models.Index(fields=['code'], name='vendors_ven_code_20e9a8_idx'), models.Index(fields=['country'], name='vendors_ven_country_ff38c7_idx'), models.Index(fields=['is_active'], name='vendors_ven_is_acti_5c8a37_idx'), models.Index(fields=['email'], name='vendors_ven_email_3112dd_idx')],
            },
        ),
    ]
